### ISSUE TITLE
ressources to get linuxstamp running

### ISSUE THREAD

**Issue by vchrizz** [pthomas/linuxstamp#1]
hi,
sorry to open up an issue, i thought i contact you this way directly.
im cleaning up my old pile of embedded devices and am now trying to get the linuxstamp (rev 1.0.2) running.

it basically boots:
```
Linux version 2.6.36-rc3+ (pthomas@black) (gcc version 4.3.2 (crosstool-NG-1.3.1) ) #39 Sat Jun 25 21:15:26 MST 2011
CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=00053177
CPU: VIVT data cache, VIVT instruction cache
Machine: Atmel AT91SAM9G20-EK
```
but is unable to load the rootfs from sd/mmc, because the sdcard seemingly died and i cant find some image or prepared rootfs to put in a new sdcard.

```
Waiting 4sec before mounting root device...
Root-NFS: No NFS server available, giving up.
VFS: Unable to mount root fs via NFS, trying floppy.
VFS: Cannot open root device "mmcblk0p1" or unknown-block(2,0)
Please append a correct "root=" boot option; here are the available partitions:
Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(2,0)
[<c002e2e4>] (unwind_backtrace+0x0/0xec) from [<c02a05c0>] (panic+0x4c/0x180)
[<c02a05c0>] (panic+0x4c/0x180) from [<c00090d8>] (mount_block_root+0x1d4/0x21c)
[<c00090d8>] (mount_block_root+0x1d4/0x21c) from [<c0009388>] (prepare_namespace+0x164/0x1c8)
[<c0009388>] (prepare_namespace+0x164/0x1c8) from [<c00085f8>] (kernel_init+0x10c/0x150)
[<c00085f8>] (kernel_init+0x10c/0x150) from [<c002a804>] (kernel_thread_exit+0x0/0x8)
```
sure i found the instructions in the [wiki](http://www.opencircuits.com/Linuxstamp) but am hoping that i dont have to go through setting up the whole development environment and compile kernel, create rootfs manually and so on.

so my question is, do you have some ressources still saved that i could download/use?

btw. links on wiki with http://linuxstamp.budgetdedicated.com/ are all dead.

thanks in advance!
br chris

**Comment by pthomas** [comment]
Hi Chris,

This should be pretty strait forward. I have several root filesystems that
can be put on a new uSD. The last emdebian fs I have, I just put on github
here:
https://github.com/pthomas/linuxstamp/blob/master/rootfs/grip_wheezy_20140427.tar.bz2

I have newer jessie & stretch debian root filesystems, but they are too
large to put on github directly.

Also it looks like the kernel output from below is trying to use nfs for
the root filesystem rather than the uSD. You'll want to make sure the
bootargs is correct in u-boot.

thanks,
Paul

**Comment by vchrizz** [comment]
hi paul,

thanks for getting back to me and thanks for the image!
basically i want to get this running with any version so i may customize from a working base :)

i've put it on a new card, it mounted successfully but hangs here forever:
```
Waiting 4sec before mounting root device...
mmc0: host does not support reading read-only switch. assuming write-enable.
mmc0: new SD card at address ecb9
mmcblk0: mmc0:ecb9 SU01G 942 MiB
 mmcblk0: p1
EXT3-fs: barriers not enabled
kjournald starting.  Commit interval 5 seconds
EXT3-fs (mmcblk0p1): using internal journal
EXT3-fs (mmcblk0p1): recovery complete
EXT3-fs (mmcblk0p1): mounted filesystem with ordered data mode
VFS: Mounted root (ext3 filesystem) on device 179:1.
Freeing init memory: 132K
request_module: runaway loop modprobe binfmt-464c
request_module: runaway loop modprobe binfmt-464c
request_module: runaway loop modprobe binfmt-464c
request_module: runaway loop modprobe binfmt-464c
request_module: runaway loop modprobe binfmt-464c

```
from bootargs i removed nfs, so it looks like this now:
bootcmd=nand read 0x20800000 0xa0000 0x200000; bootm 0x20800000
bootargs=mem=32M console=ttyS0,115200 rootdelay=4 noinitrd root=/dev/mmcblk0p1 rootfstype=ext3 rw debug

as i already have debug option in bootargs, is there anything i can do to see any more verbose output where it seems to hang?

thanks,
chris

**Comment by pthomas** [comment]
Hmm, ok try grip_squeeze_20110512.tar.bz2 that I just pushed. I see
this is the fs referenced in the wiki anyway. It looks like it is
correctly mounting the fs.

-Paul

**Comment by vchrizz** [comment]
great! this one works! thank you very much!
btw. what is the default password of the root user in this image?

how about linking to that image in the wiki to fix the dead link(s)?
(then this issue can be closed i guess)

edit: just noticed all emdebian related has gone, even mirrors give 404 if the dns at least is resolving.
.. so i would be interested in your debian stretch image too, how could you make that available for me? :) i could provide a server if that helps anyhow?

```
EXT3-fs: barriers not enabled
kjournald starting.  Commit interval 5 seconds
EXT3-fs (mmcblk0p1): using internal journal
EXT3-fs (mmcblk0p1): recovery complete
EXT3-fs (mmcblk0p1): mounted filesystem with ordered data mode
VFS: Mounted root (ext3 filesystem) on device 179:1.
Freeing init memory: 132K
INIT: version 2.88 booting
Using makefile-style concurrent boot in runlevel S.
Starting the hotplug events dispatcher: udevd.
Synthesizing the initial hotplug events...done.
Waiting for /dev to be fully populated...done.
Activating swap...done.
Cleaning up ifupdown....
Setting up networking....
Loading kernel modules...done.
Activating lvm and md swap...done.
Checking file systems...fsck from util-linux-ng 2.17.2
done.
Mounting local filesystems...done.
Activating swapfile swap...done.
Cleaning up temporary files....
Configuring network interfaces...Ignoring unknown interface lo=lo.
done.
Cleaning up temporary files....
Setting kernel variables ...done.
INIT: Entering runlevel: 2
Using makefile-style concurrent boot in runlevel 2.
Starting OpenBSD Secure Shell server: sshdsshd (719): /proc/719/oom_adj is deprecated, please use /proc/719/oom_score_adj instead.
.

rdate: time-a.timefreq.bldrdoc.gov: Name or service not known
startpar: service(s) returned failure: rc.local ... failed!

Debian GNU/Linux 6.0 ls2 ttyS0

ls2 login:
```

cheers,
chris
